### ISSUE TITLE
about retrieval result using given pre-trained model

### ISSUE THREAD

**Issue by YuqiHUO** [TengdaHan/CoCLR#10]
Hi, thanks for the amazing work. I used the ucf101-infonce pre-trained model you released. I test the retrieval result use eval/main_classifier.py. Surprisingly, I get 
NN@1 | @5 | @10 | @20 | @50
36.11 | 52.31 | 61.72 | 71 | 82.05
which is much higher (3%) than you reported 33.1% of NN@1. Can you verify the result of the pre-trained model? Does anyone meet a similar problem? Is there something different between the default config in the code and you adopted?

**Comment by TengdaHan** [comment]
Thank you for pointing out. 
There could be some small variations after I refactor and clean my code... 
I don't think +3% variation is 'much higher' for InfoNCE baseline, I found the exact UCF101-CoCLR checkpoint I provided also get 1-2% higher in NN@1. 
I will check/update all of them later.
