### ISSUE TITLE
Split files for UCF101

### ISSUE THREAD

**Issue by acewjh** [TengdaHan/CoCLR#11]
Hello, I'm trying to run main_coclr.py on UCF101 dataset, while the split files are not given, i.e. train_split1.csv. Would you please upload these files or the script to generate them from the official txt split files? Thanks a lot.

**Comment by TengdaHan** [comment]
Hi, you can use the script here: https://github.com/TengdaHan/DPC/blob/master/process_data/src/write_csv.py,
it's a csv file containing:
```
/your_path/ApplyEyeMakeup/v_ApplyEyeMakeup_g01_c01/,num_frames
/your_path/ApplyEyeMakeup/v_ApplyEyeMakeup_g01_c02/,num_frames
...
```
I will add this instruction to this repo later.
