### ISSUE TITLE
about 'flow' data

### ISSUE THREAD

**Issue by junmin98** [TengdaHan/CoCLR#12]
Thank you for letting me know about the issue I posted last time. 
I was studying your code, but I got curious again, so I came to ask you again.

I want to run 'main_coclr.py'
So I'm getting the ucf101's optical flow using the code to extract the frame and flow from your MemDPC github.

Looking at the code, I had to convert flow data to .lmdb. Can I get it using 'convert_video_to_lmdb.py' just like changing frame data to lmdb?
for example, (in convert_video_to_lmdb.py in dataset)
make_dataset_lmdb(dataset_path='mypath/UCF101/flow',
                      filename='mypath/UCF101/ucf101_tvl1.lmdb.lmdb')

**Comment by TengdaHan** [comment]
Yes, that's what I did. Optical flow files are treated as images.

But converting to lmdb is not necessary, you can directly load images like my previous script https://github.com/TengdaHan/MemDPC/blob/master/memdpc/dataset.py, with some modification in `__getitem__` to apply augmentation correctly.

**Comment by June01** [comment]
Hi Tengda, I am also wondering, there are a pair of images to descripe the optical flow  of an image -- (flow_x, flow_y), how could you load two of them together? It seems not the same with rgb images.

The training stage works very well with rgb images, but when I am using your flow lmdb to train flow batch, it raises an error:
```
raw = msgpack.loads(txn.get(self.get_video_id['ApplyEyeMakeup/v_ApplyEyeMakeup_g08_c01'].encode('ascii')))
  File "msgpack/_unpacker.pyx", line 195, in msgpack._cmsgpack.unpackb
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```
That would be great if it happened to you or you know the anser.

**Comment by TengdaHan** [comment]
Flow format: I append the third empty channel to the flow_x and flow_y, then I get a three-channel array for one optical flow file, I compress it using jpeg - this gives some flexibility to use some image-wise augmentations like colour-jittering. Code here: https://github.com/TengdaHan/MemDPC/blob/11f03299496c55d3ecae670752e958d8ce0c80fb/process_data/src/extract_ff.py#L53 

Loading with msgpack error: probably check here: https://github.com/TengdaHan/CoCLR#dataset and https://github.com/TengdaHan/CoCLR/issues/32 .

**Comment by June01** [comment]
Thanks. It resolves my problem quite well.
