### ISSUE TITLE
CoCLR using only RGB frame(1 stream)

### ISSUE THREAD

**Issue by junmin98** [TengdaHan/CoCLR#15]
It took too long to extract the flow, so I am trying to train coclr using only rgb frames(1-stream). Is that possible?

I think it's possible when you see this part in Table 2 of your paper
![image](https://user-images.githubusercontent.com/60462076/101024225-26224700-35b7-11eb-8d8b-392367cbde91.png)

If possible, can you tell me how to train using only rgb frames?

ps. Thanks for always answering in detail!

**Comment by TengdaHan** [comment]
* train CoCLR using only RGB frames - that would not be self-supervised "co-training" then... our key idea is to use one view of the data to help the other. 
* Table2 - this is the evaluation results (accuracy on action classification task). Self-supervised pre-training with CoCLR will give you two models, one takes RGB inputs and one takes Flow inputs. We can evaluate action classification with the RGB model (row 1, 3), or with Flow model, or with two-stream model by averaging the probability of the two (row 2, 4).
* I have a UCF101 TVL1 optical flow shared in this address: http://www.robots.ox.ac.uk/~htd/tar/ucf101_flow_lmdb.tar 
It's 20.5GB, you need to `tar -xvf ucf101_flow_lmdb.tar`, it contains the lmdb file I used. Welcome to try. 
* I will update a detailed instruction for reproducing our results this week, stay tuned.

**Comment by junmin98** [comment]
Thank you so much for sharing the flow dataset!! 
Your explanation made me understand again. Thank you so much!

If you don't mind, could you share flow data of other datasets?

**Comment by TengdaHan** [comment]
I am afraid I don't have enough space to host more datasets on our server. 
You can use GPU to extract the optical flow which could definitely accelerate a lot, if you compiled OpenCV with GPU support by yourself:
https://github.com/TengdaHan/CoCLR/issues/5#issuecomment-735889717

**Comment by junmin98** [comment]
ok. thank you so much!
