### ISSUE TITLE
config about fully-finetune

### ISSUE THREAD

**Issue by YuqiHUO** [TengdaHan/CoCLR#18]
Hi, im curious about the config when you fully-finetune the pre-trained model.
What bs/lr/wd do you use? Do you set the lr of backbone 1/10 to the lr of the fc layer or keep them the same?
Thanks!

Best Regards,
Yuqi

**Comment by TengdaHan** [comment]
For finetuning the pre-trained model, I use batch_size=32, wd=1e-3, lr=1e-3.
I use smaller (1/10) lr for the backbone: https://github.com/TengdaHan/CoCLR/blob/main/eval/main_classifier.py#L139

**Comment by YuqiHUO** [comment]
> For finetuning the pre-trained model, I use batch_size=32, wd=1e-3, lr=1e-3.
> I use smaller (1/10) lr for the backbone: https://github.com/TengdaHan/CoCLR/blob/main/eval/main_classifier.py#L139

Hi, sorry that I still can't reproduce the 81.4 (top-1 at fully-finetune of COCLR-RGB) using your given ep182.pth.tar. I know that I must set some config wrong. How many epochs do you finetune and what's your schedule? What optimizer do you use? Adam or sgd?
Thanks, your answer helps me a lot!

Best Regards,
Yuqi
