### ISSUE TITLE
config for linear probe

### ISSUE THREAD

**Issue by wbxzky** [TengdaHan/CoCLR#19]
Hi Tengda,
Thanks for sharing the code! I have a question about your linear probe setting.
I use your released UCF101 pretrained rgb model to train a fc layer. To do that I run the command with your code's default setting:
`python3 main_classifier.py --train_what last --pretrain /../CoCLR-ucf101-rgb-128-s3d-ep182.tar` 

After that I got a new pretrained model and I reload it to evaluate the s3d backbone:
`python3 main_classifier.py --test /../epoch9.pth.tar --ten_crop` 

Finally I got Acc@1 67.9 on UCF-101 test split 1, which is lower than your report result 70.2.
So I want to ask is there something wrong with my training and testing processing?  could you please share me your config and steps to train a fc layer for linear probe?
Thanks, looking forward to your reply.

**Comment by junmin98** [comment]
hello. 
Hello. I'm trying to do exactly what you asked
i.e. python3 main_classifier.py --test {pretrained_model_path} --ten_crop ...

I got the following error. Could you please tell me how I solved it?
>> File "main_classifier.py", line 490, in test_10crop
    vname = vname[0]
UnboundLocalError: local variable 'vname' referenced before assignment

**Comment by junmin98** [comment]
> Hello. I'm trying to do exactly what you asked
> i.e.
> `python3 main_classifier.py --test {pretrained_model_path} --ten_crop ... `
> I got the following error. Could you please tell me how I solved it?
> 
> > > File "main_classifier.py", line 490, in test_10crop
> > > vname = vname[0]
> > > UnboundLocalError: local variable 'vname' referenced before assignment

I solved this problem by referring to the MemDPC code.

**Comment by TengdaHan** [comment]
I upload detailed instructions in readme now. Sorry for the delay. @wbxzky I think reducing lr by step scheduler is important. The 9-th epoch you evaluated may not be well-trained.
