### ISSUE TITLE
Questions about linear probe and fine tune

### ISSUE THREAD

**Issue by junmin98** [TengdaHan/CoCLR#23]
I have now completed the CoCLR training course. In other words, it was completed up to Cycle 2.
So I'm trying to do a downstream task.

for linear probe
`CUDA_VISIBLE_DEVICES=0 main_classifier.py --pretrain {cycle2_rgb_pretrained.pth.tar}`

i got a new pretrained model.

so, to obtain the test result for action recognition
`CUDA_VISIBLE_DEVICES=2,3 main_classifier.py --test {new_pretrained_epoch9.pth.tar} --ten_crop`

but I got an error

Traceback (most recent call last):
  File "main_classifier.py", line 822, in <module>
    main(args)
  File "main_classifier.py", line 204, in main
    test_10crop(test_dataset, model, ce_loss, transform_test_cuda, device, epoch, args)
  File "main_classifier.py", line 482, in test_10crop
    for idx, (input_seq, target) in tqdm(enumerate(data_loader), total=len(data_loader)):
  File "/home/cvip-lab/anaconda3/envs/junmin/lib/python3.6/site-packages/tqdm/std.py", line 1158, in __iter__
    for obj in iterable:
  File "/home/cvip-lab/anaconda3/envs/junmin/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/cvip-lab/anaconda3/envs/junmin/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1065, in _next_data
    return self._process_data(data)
  File "/home/cvip-lab/anaconda3/envs/junmin/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/home/cvip-lab/anaconda3/envs/junmin/lib/python3.6/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
PIL.UnidentifiedImageError: Caught UnidentifiedImageError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/cvip-lab/anaconda3/envs/junmin/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/cvip-lab/anaconda3/envs/junmin/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/cvip-lab/anaconda3/envs/junmin/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "../dataset/lmdb_dataset.py", line 182, in __getitem__
    seq = [pil_from_raw_rgb(raw[i]) for i in frame_index]
  File "../dataset/lmdb_dataset.py", line 182, in <listcomp>
    seq = [pil_from_raw_rgb(raw[i]) for i in frame_index]
  File "../dataset/lmdb_dataset.py", line 39, in pil_from_raw_rgb
    return Image.open(BytesIO(raw)).convert('RGB')
  File "/home/cvip-lab/anaconda3/envs/junmin/lib/python3.6/site-packages/PIL/Image.py", line 2944, in open
    "cannot identify image file %r" % (filename if filename else fp)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f6f3d880fc0>

**Comment by junmin98** [comment]
> I have now completed the CoCLR training course. In other words, it was completed up to Cycle 2.
> So I'm trying to do a downstream task.
> 
> for linear probe
> `CUDA_VISIBLE_DEVICES=0 main_classifier.py --pretrain {cycle2_rgb_pretrained.pth.tar}`
> 
> i got a new pretrained model.
> 
> so, to obtain the test result for action recognition
> `CUDA_VISIBLE_DEVICES=2,3 main_classifier.py --test {new_pretrained_epoch9.pth.tar} --ten_crop`
> 
> but I got an error
> 
> Traceback (most recent call last):
> File "main_classifier.py", line 822, in
> main(args)
> File "main_classifier.py", line 204, in main
> test_10crop(test_dataset, model, ce_loss, transform_test_cuda, device, epoch, args)
> File "main_classifier.py", line 482, in test_10crop
> for idx, (input_seq, target) in tqdm(enumerate(data_loader), total=len(data_loader)):
> File "/home/cvip-lab/anaconda3/envs/junmin/lib/python3.6/site-packages/tqdm/std.py", line 1158, in **iter**
> for obj in iterable:
> File "/home/cvip-lab/anaconda3/envs/junmin/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 435, in **next**
> data = self._next_data()
> File "/home/cvip-lab/anaconda3/envs/junmin/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1065, in _next_data
> return self._process_data(data)
> File "/home/cvip-lab/anaconda3/envs/junmin/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
> data.reraise()
> File "/home/cvip-lab/anaconda3/envs/junmin/lib/python3.6/site-packages/torch/_utils.py", line 428, in reraise
> raise self.exc_type(msg)
> PIL.UnidentifiedImageError: Caught UnidentifiedImageError in DataLoader worker process 0.
> Original Traceback (most recent call last):
> File "/home/cvip-lab/anaconda3/envs/junmin/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
> data = fetcher.fetch(index)
> File "/home/cvip-lab/anaconda3/envs/junmin/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
> data = [self.dataset[idx] for idx in possibly_batched_index]
> File "/home/cvip-lab/anaconda3/envs/junmin/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in
> data = [self.dataset[idx] for idx in possibly_batched_index]
> File "../dataset/lmdb_dataset.py", line 182, in **getitem**
> seq = [pil_from_raw_rgb(raw[i]) for i in frame_index]
> File "../dataset/lmdb_dataset.py", line 182, in
> seq = [pil_from_raw_rgb(raw[i]) for i in frame_index]
> File "../dataset/lmdb_dataset.py", line 39, in pil_from_raw_rgb
> return Image.open(BytesIO(raw)).convert('RGB')
> File "/home/cvip-lab/anaconda3/envs/junmin/lib/python3.6/site-packages/PIL/Image.py", line 2944, in open
> "cannot identify image file %r" % (filename if filename else fp)
> PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f6f3d880fc0>

Could you please provided detailed explanation regarding downstream task? (action recognition & retrieval)
I'm confused about what "feature_linear_probe.py" is for and what "main_classifier.py" is for..

**Comment by TengdaHan** [comment]
I uploaded detailed instructions in readme now. Sorry for the long delay...
