### ISSUE TITLE
what is self-acc?

### ISSUE THREAD

**Issue by junmin98** [TengdaHan/CoCLR#25]
Checking the updated code, the "self-acc" part has been newly added.
what is self-acc?

**Comment by TengdaHan** [comment]
```python
top1, top5 = calc_mask_accuracy(output, mask, (1,5))
top1_self, top5_self = calc_topk_accuracy(output, torch.zeros(B, dtype=torch.long).cuda(), (1,5))
```
It's just for monitoring purpose, to monitor the instance discrimination performance (retrieve its own augmented version) during multi-instance contrastive learning.

**Comment by junmin98** [comment]
> ```python
> top1, top5 = calc_mask_accuracy(output, mask, (1,5))
> top1_self, top5_self = calc_topk_accuracy(output, torch.zeros(B, dtype=torch.long).cuda(), (1,5))
> ```
> 
> It's just for monitoring purpose, to monitor the instance discrimination performance (retrieve its own augmented version) during multi-instance contrastive learning.

thank you for your answer. I'll be waiting for other answer too :)
