### ISSUE TITLE
How to get the 'train_split.csv' file for K400 dataset

### ISSUE THREAD

**Issue by zxzhaoeric** [TengdaHan/CoCLR#27]
Hi Tengda,

Could you please show the file structure of 'train_split.csv' for K400 dataset? When I run lmdb_dataset.py, the csv file I downloaded from the DeepMind website is not compatible with the code.

Many Thanks

**Comment by TengdaHan** [comment]
For K400, it just need to be `path, num_frames` like:
```
abseiling/0wR5jVB-WPk_000417_000427,300
abseiling/3caPS4FHFF8_000036_000046,300
```
I updated this page: https://github.com/TengdaHan/CoCLR/tree/main/process_data/data/k400 
you can check my version there.
