### ISSUE TITLE
cannot access your train/val split csv

### ISSUE THREAD

**Issue by thematrixduo** [TengdaHan/CoCLR#31]
Hi, I am trying to download your train/val split csv file here: https://github.com/TengdaHan/CoCLR/tree/main/process_data/data/k400

But it says 403 forbidden. I believe you put it in some internal-only storage?

**Comment by TengdaHan** [comment]
Right now our department's web system has some problems. I think it will be fixed soon.

**Comment by thematrixduo** [comment]
Thanks for the quick response. I have another question. Do you have the optical flows for K400 dataset or the preprocessing code for computing the optical flow? Thanks

**Comment by TengdaHan** [comment]
The server has been fixed, the link should work now.

Preprocessing code is here: https://github.com/TengdaHan/MemDPC/blob/master/process_data/src/extract_ff.py 
But I used about 20 CPU machines in parallel for about 5 days for extracting optical flow.

Unfortunately, the K400 optical flow file is too large to share. If you want to extract, I also recommend using other's GPU version of TVL1 flow as I mentioned here: https://github.com/TengdaHan/CoCLR/issues/5#issuecomment-735889717

**Comment by thematrixduo** [comment]
Great, Thanks!

**Comment by thematrixduo** [comment]
> The server has been fixed, the link should work now.
> 
> Preprocessing code is here: https://github.com/TengdaHan/MemDPC/blob/master/process_data/src/extract_ff.py
> But I used about 20 CPU machines in parallel for about 5 days for extracting optical flow.
> 
> Unfortunately, the K400 optical flow file is too large to share. If you want to extract, I also recommend using other's GPU version of TVL1 flow as I mentioned here: [#5 (comment)](https://github.com/TengdaHan/CoCLR/issues/5#issuecomment-735889717)

I tried to use your code for preprocessing K400. However it still hasn't finished running after 7 days, and I am using a 80-CPU-core machine. Can you share what is your time per iteration? For me it range from 45s/it to 644s/it

**Comment by TengdaHan** [comment]
Sorry for the late reply... I don't remember the time per iter, but it's usually consistent for each 10s video clip.
