### ISSUE TITLE
UCF101 Flow Download Link Broken

### ISSUE THREAD

**Issue by sherrychen127** [TengdaHan/CoCLR#33]
Hi, 

I'm having trouble accessing the link for downloading the ucf101 flow lmdb data: http://thor.robots.ox.ac.uk/~vgg/data/CoCLR/ucf101_flow_lmdb.tar 
It would return a 'ERR_CONNECTION_REFUSED' error.

**Comment by TengdaHan** [comment]
Temporary could try http://www.robots.ox.ac.uk/~htd/tar/ucf101_flow_lmdb.tar for flow dataset.

**Comment by sherrychen127** [comment]
thanks!
