### ISSUE TITLE
How to generate corresponding 'video_source.json'？

### ISSUE THREAD

**Issue by wzy1845** [TengdaHan/CoCLR#38]
First of all, thank you so much for sharing source code.
With the newly updated code, I'm going to run the code for my own dataset.
Can you tell me how to generate corresponding 'video_source.json' from the new dataset directory?  Can you share the source code?
Thank you so much!

**Comment by TengdaHan** [comment]
The purpose of "video_source.json" file is for datasets like UCF101, where it has ''sibling clips" that cropped from the same source video. In "video_source.json", clips from the same source have the same index (order doesn't matter at all). 

In your own dataset, if your clips are from different source videos (I guess it's your case), just create the video_source.json file like:
```
{"video1.mp4": 1,
"video2.mp4": 2,
"video3.mp4": 3,
...}
```
such that every video has a different index. The order doesn't matter.
