### ISSUE TITLE
AttributeError: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by ZihuaEvan** [TengdaHan/CoCLR#39]
Hi tengda,

When I called lmdb_dataset.py in main_classifier.py , I got the following error:

Frame Dataset from "/root/coclr/dataset/../process_data/data/ucf101" has #class 101
Traceback (most recent call last):
  File "main_classifier.py", line 818, in <module>
    main(args)
  File "main_classifier.py", line 200, in main
    test_retrieval(model, ce_loss, transform_test_cuda, device, epoch, args)
  File "main_classifier.py", line 574, in test_retrieval
    train_dataset = d_class(mode='train', 
  File "/root/coclr/eval/../dataset/lmdb_dataset.py", line 174, in __init__
    super(UCF101LMDB, self).__init__(**kwargs)
  File "/root/coclr/eval/../dataset/lmdb_dataset.py", line 96, in __init__
    self.get_video_id = dict(zip([i.decode() for i in self.db_order], 
  File "/root/coclr/eval/../dataset/lmdb_dataset.py", line 96, in <listcomp>
    self.get_video_id = dict(zip([i.decode() for i in self.db_order], 
AttributeError: 'str' object has no attribute 'decode'

Thank you for your reply.

**Comment by TengdaHan** [comment]
It looks like msgpack version issue. 
Have you tried this note: https://github.com/TengdaHan/CoCLR#dataset
or https://github.com/TengdaHan/CoCLR/issues/32 ? 
Basically, the new version of msgpack package has different default settings when loading data. Loading everything as 'raw=True' can revert back to earlier settings.

**Comment by ZihuaEvan** [comment]
The problem has been solved. Thanks for your answering!
BTW: The numpy version may cause error in line122 in lmdb_dataset.py: 
seq_idx = seq_idx.flatten(0)
And change it to: seq_idx = seq_idx.flatten() will be fine.
