### ISSUE TITLE
lmdb_dataset.py  txn.get(self.get_video_id[name].encode('ascii')))

### ISSUE THREAD

**Issue by xiaochehe** [TengdaHan/CoCLR#41]
![20210722155421](https://user-images.githubusercontent.com/16096446/126606808-731d0c7c-4254-487d-b52f-14deb1be7be5.png)

When I ran the program, I found "txn.get(self.get_video_id[name].encode('ascii')))" severely limiting the speed. Meanwhile, CPU is free.
I don't know what the problem is.
Hope to get help. Thanks

**Comment by TengdaHan** [comment]
Is this issue related? https://github.com/TengdaHan/CoCLR/issues/32

**Comment by xiaochehe** [comment]
> Is this issue related? #32

I think it is not:(

**Comment by xiaochehe** [comment]
I find the problem:)

I have set:
self.db_length = msgpack.loads(txn.get(b'__len__'), raw=True)
 self.db_keys = msgpack.loads(txn.get(b'__keys__'), raw=True)
  self.db_order = msgpack.loads(txn.get(b'__order__'), raw=True)

I am a fool!!!!!!

**Comment by xiaochehe** [comment]
Unfortunately :(. I still don't solve the problem.

The speed of dataloader is limited by the code "txn.get(self.get_video_id[name].encode('ascii')))", "txn.get()". And I think the problem is related to lmdb and not related to msgpack. 

Can you provide your conda environment?

Following is IO analysis, when I run the code.
![1](https://user-images.githubusercontent.com/16096446/126730109-b4bb36b6-07cc-4aa5-b566-d895afeb414e.png)

**Comment by TengdaHan** [comment]
The environment.yml that I used for this repo: https://github.com/TengdaHan/CoCLR/blob/main/environment_pt14.yml
