### ISSUE TITLE
Issue about DistributedDataParallel（DDP）

### ISSUE THREAD

**Issue by ZihuaEvan** [TengdaHan/CoCLR#42]
Hi，thank you for your work! 
When I was training the weight in model.pretrain.py, it showed that I have to use DistributedDataParallel（DDP）.  Is it means that it have to train on different server by multi-card training ?  And I failed my training on one mechine with 2 GPUs(1080ti)
Thank you for your attention！

**Comment by TengdaHan** [comment]
Hi, the command I provided in the [pretrain-instruction](https://github.com/TengdaHan/CoCLR#pretrain-instruction) or [here](https://github.com/TengdaHan/CoCLR/blob/main/main_coclr.py#L522) should work on **a single server with 2GPUs**. What error message did you get?

**Comment by ZihuaEvan** [comment]
Hi, I ran it on the server and got this error. Is it means that I should set the local rank for each GPU? Thank you for your reply!
Best wishes.



发件人: Tengda Han
发送时间: 2021年9月27日 10:03
收件人: TengdaHan/CoCLR
抄送: ZihuaEvan; Author
主题: Re: [TengdaHan/CoCLR] Issue aboutDistributedDataParallel（DDP） (#42)

Hi, the command I provided in the pretrain-instruction or here should work on a single server with 2GPUs. What error message did you get?
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ZihuaEvan** [comment]
Is it possible that the memory of cards are not enough?
Here is the error message:
subprocess.CalledProcessError: Command '['/seu_share/apps/anaconda3/bin/python3', '-u', '/seu_share/home/220205287/COCLR/main_coclr.py', '--local_rank=1']' died with <Signals.SIGBUS: 7>.
