### ISSUE TITLE
Can we design a downstream task for action detection?

### ISSUE THREAD

**Issue by napohou** [TengdaHan/CoCLR#47]
Hi authors,
If yes, can you show me some demo code for such a downstream task?

**Comment by napohou** [comment]
any update?

**Comment by TengdaHan** [comment]
Hi, thank you for your interest in our work.
The key contribution in our paper is to show how CoCLR helps representation learning (evaluated by action classification and action retrieval). 
Action detection is out of the scope of this repo.

Generally, if you want to use CoCLR as a representation for action detection, 
you can take our pre-trained weight as a feature extractor. 
Then train a 1-stage (e.g. DETR on time axis) or 2-stage (proposal+classify) action detector.

**Comment by napohou** [comment]
I see. Thanks @TengdaHan 
Do we have a demo code for that?

**Comment by TengdaHan** [comment]
No. 

But you can learn from https://github.com/jayleicn/moment_detr.

**Comment by napohou** [comment]
I see. Thanks @TengdaHan
