### ISSUE TITLE
A question about convert_video_to_lmdb.py

### ISSUE THREAD

**Issue by chenqz1998** [TengdaHan/CoCLR#52]
Hi Tengda,
I am making my dataset via your public code: ([resize_video.py] first (https://github.com/TengdaHan/MemDPC/blob/master/process_data/src/resize_video.py), [resize_video.py](https://github.com/TengdaHan/MemDPC/blob/master/process_data/src/resize_video.py) then and [convert_video_to_lmdb.py](https://github.com/TengdaHan/CoCLR/blob/main/dataset/convert_video_to_lmdb.py). But when I convert video to lmdb, this mistake occur and I cannot solve it though I google a lot and change change the msgpack version. If you can help me solve it, I will appreciate you a lot. Many thanks!
![7d08577d3698e0e3b58bbb679f209f4](https://user-images.githubusercontent.com/42370559/198302379-128966dc-1eb0-496c-8061-28aaf6be41fe.jpg)

**Comment by TengdaHan** [comment]
Hi, I've never seen this error before. I'm afraid I cannot help much with this.
If you really could not fix this, you can just save the videos and load from them with some toolboxes like https://github.com/dmlc/decord.

**Comment by chenqz1998** [comment]
I run convert_video_to_lmdb.py on Windows rather than Linux, and the bug is solved, though I have no idea why.
