### ISSUE TITLE
Download Link of Checkpoint

### ISSUE THREAD

**Issue by ZiyuGuo99** [TengdaHan/CoCLR#53]
Thanks for your excellent work!

I found that the download links in https://github.com/TengdaHan/CoCLR#pretrained-weights are invalid now. Could you update new ones?
Looking forward to your reply and sorry if it was my mistake. : )

**Comment by TengdaHan** [comment]
Which link doesn't work for you? 
Have you tried downloading by `wget http://www.robots.ox.ac.uk/~htd/coclr/CoCLR-k400-rgb-128-s3d.pth.tar`? From my side, these links still work for me if you download with `wget`.

**Comment by ZiyuGuo99** [comment]
Sorry, I found that it was the network problem of my server. I changed another one and it worked.
Thanks a lot for your time and reply!
