### ISSUE TITLE
tensors are not compatible in size

### ISSUE THREAD

**Issue by caicj15** [TengdaHan/CoCLR#8]
Thanks for your code, it helps me a lot. I have some questions:

1. I perform linear evaluation with main_classifier.py after pretraining with infonce. However, in train_one_epoch,validate, test_10crop, the size of input_seq for model is not compatible. The input_seq have to many dimensions. 
2. Do you use pytorch with low version? Some functions, like data.Sequential, can't be found.
3. The img resolution is always 128 in your  work? Including the linear evaluation and fine tune protocol?

**Comment by TengdaHan** [comment]
Hi, 
1. Dimension fixed now, I missed a squeezing operation.
2. I use PyTorch 1.2-1.4, but newer version should work as well. It should be `data.SequentialSampler`, fixed now.
3. Yes. A higher resolution like 224x224 will definitely give better performance, but the pretraining will take longer. We cannot afford that experiment, for now.
