### ISSUE TITLE
Where is the code of `select_resnet` in pretrain.CoCLR?

### ISSUE THREAD

**Issue by XFeiF** [TengdaHan/CoCLR#9]
https://github.com/TengdaHan/CoCLR/blob/dec473830800bb9ca24781ad19e5d53678d61953/model/pretrain.py#L282  
I do not find the code of `selec_resnet` in other files. Through the parameters used by it, it is different from the `select_backbone` above? If it is a spelling mistake, please correct it or maybe you can upload the code of it.  
   
Thanks.

**Comment by TengdaHan** [comment]
Thank you for pointing out. It should be `select_backbone` function. Corrected now.
